#!/bin/bash
echo "=== DigitalOcean Debug Script ==="
echo "Current working directory:"
pwd
echo ""
echo "Contents of current directory:"
ls -la
echo ""
echo "Contents of dist directory:"
ls -la dist/ 2>/dev/null || echo "dist directory not found"
echo ""
echo "Looking for production.js:"
find . -name "production.js" -type f 2>/dev/null
echo ""
echo "Environment variables:"
echo "NODE_ENV: $NODE_ENV"
echo "PORT: $PORT"
echo ""
echo "Attempting to run production.js with different paths:"
echo "1. Trying: node dist/production.js"
test -f dist/production.js && echo "File exists: dist/production.js" || echo "File NOT found: dist/production.js"
echo ""
echo "2. Trying: node ./dist/production.js"  
test -f ./dist/production.js && echo "File exists: ./dist/production.js" || echo "File NOT found: ./dist/production.js"
echo ""
echo "3. Trying: node /workspace/dist/production.js"
test -f /workspace/dist/production.js && echo "File exists: /workspace/dist/production.js" || echo "File NOT found: /workspace/dist/production.js"