name: autobid-tj
services:
- name: web
  source_dir: /
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SESSION_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SPACES_ENDPOINT
    value: "ams3.digitaloceanspaces.com"
  - key: SPACES_BUCKET
    value: "autobid-storage"
  - key: SPACES_REGION
    value: "ams3"
  - key: SPACES_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SPACES_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SMS_API_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SMS_API_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PORT
    value: "8080"